# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and test application"
  lane :test do |options|
    # add actions here: https://docs.fastlane.tools/actions
    scan(
      derived_data_path: "./DerivedData",
      output_directory: "./reports",
      scheme: "QuizApp"
    )
    slather(
      build_directory: "./DerivedData", 
      output_directory: "./reports",
      scheme: "QuizApp",
      proj: "QuizApp.xcodeproj",
      sonarqube_xml: true,
      github: true,
      arch: "x86_64"
    )
    lizard(
      source_folder: ".", 
      language: "swift", 
      export_type: "xml", 
      report_file: "reports/lizard-report.xml"
    )
    swiftlint(
      output_file: "./reports/swiftlint.txt", 
      ignore_exit_status: true
    )
    sonar(
      sonar_login: options[:sonar_login],
    )
  end
end
